/**
 * Sunnyside raw assets, crops and tiles are not stored in this repository
 * If you want access to these, you must download the asset pack from: https://danieldiggle.itch.io/sunnyside
 */

import { CONFIG } from "lib/config";

export const SUNNYSIDE = {
  soil: {
    sand_dug: `https://sunflower-land.com/testnet-assets/crops/sand_dug.png`,
    sand_hill: `https://sunflower-land.com/testnet-assets/crops/sand_hill.png`,
    soil_dry: `https://sunflower-land.com/testnet-assets/crops/soil_dry.png`,
    soil_not_fertile: `https://sunflower-land.com/testnet-assets/crops/soil_not_fertile.png`,
    soil2: `https://sunflower-land.com/testnet-assets/crops/soil2.png`,
  },
  animals: {
    bird: `https://sunflower-land.com/testnet-assets/animals/bird_sheet.png`,
  },
  vfx: {
    blinking: `https://sunflower-land.com/testnet-assets/vfx/blinking.png`,
  },
  icons: {
    angry: `https://sunflower-land.com/testnet-assets/icons/angry.png`,
    arrow_down: `https://sunflower-land.com/testnet-assets/icons/arrow_down.png`,
    arrow_left: `https://sunflower-land.com/testnet-assets/icons/arrow_left.png`,
    arrow_right: `https://sunflower-land.com/testnet-assets/icons/arrow_right.png`,
    arrow_up: `https://sunflower-land.com/testnet-assets/icons/arrow_up.png`,
    basket: `https://sunflower-land.com/testnet-assets/icons/basket.png`,
    cancel: `https://sunflower-land.com/testnet-assets/icons/cancel.png`,
    close: `https://sunflower-land.com/testnet-assets/icons/close.png`,
    confirm: `https://sunflower-land.com/testnet-assets/icons/confirm.png`,
    disc_large: `https://sunflower-land.com/testnet-assets/icons/disc_large.png`,
    disc: `https://sunflower-land.com/testnet-assets/icons/disc.png`,
    drag: `https://sunflower-land.com/testnet-assets/icons/drag.png`,
    dragging: `https://sunflower-land.com/testnet-assets/icons/dragging.png`,
    expand: `https://sunflower-land.com/testnet-assets/icons/expand.png`,
    expression_alerted: `https://sunflower-land.com/testnet-assets/icons/expression_alerted.png`,
    expression_chat: `https://sunflower-land.com/testnet-assets/icons/expression_chat.png`,
    expression_confused: `https://sunflower-land.com/testnet-assets/icons/expression_confused.png`,
    fish: `https://sunflower-land.com/testnet-assets/icons/fish.png`,
    hammer: `https://sunflower-land.com/testnet-assets/icons/hammer.png`,
    heart: `https://sunflower-land.com/testnet-assets/icons/heart.png`,
    helios: `https://sunflower-land.com/testnet-assets/icons/helios_icon.png`,
    indicator: `https://sunflower-land.com/testnet-assets/icons/indicator.png`,
    plant: `https://sunflower-land.com/testnet-assets/icons/plant.png`,
    player_small: `https://sunflower-land.com/testnet-assets/icons/player_small.png`,
    player: `https://sunflower-land.com/testnet-assets/icons/player.png`,
    sad: `https://sunflower-land.com/testnet-assets/icons/sad.png`,
    search: `https://sunflower-land.com/testnet-assets/icons/search.png`,
    seedling: `https://sunflower-land.com/testnet-assets/icons/seedling.png`,
    seeds: `https://sunflower-land.com/testnet-assets/icons/seeds.png`,
    stopwatch: `https://sunflower-land.com/testnet-assets/icons/stopwatch.png`,
    sunflorea: `https://sunflower-land.com/testnet-assets/icons/sunflorea.png`,
    sword: `https://sunflower-land.com/testnet-assets/icons/sword.png`,
    timer: `https://sunflower-land.com/testnet-assets/icons/timer.png`,
    treasure: `https://sunflower-land.com/testnet-assets/icons/treasure_icon.png`,
    water: `https://sunflower-land.com/testnet-assets/icons/water.png`,
    happy: `https://sunflower-land.com/testnet-assets/icons/happy.png`,
    neutral: `https://sunflower-land.com/testnet-assets/icons/neutral.png`,
    stressed: `https://sunflower-land.com/testnet-assets/icons/expression_stress.png`,
    death: `https://sunflower-land.com/testnet-assets/icons/expression_attack.png`,
    plus: `https://sunflower-land.com/testnet-assets/icons/plus.png`,
    minus: `https://sunflower-land.com/testnet-assets/icons/minus.png`,
    wardrobe: `https://sunflower-land.com/testnet-assets/icons/wardrobe.png`,
    chevron_right: `https://sunflower-land.com/testnet-assets/icons/chevron_right.png`,
    dig_icon: `https://sunflower-land.com/testnet-assets/icons/dig_icon.png`,
    plant_icon: `https://sunflower-land.com/testnet-assets/icons/plant_icon.png`,
    chop_icon: `https://sunflower-land.com/testnet-assets/icons/chop_icon.png`,
    click_icon: `https://sunflower-land.com/testnet-assets/icons/click_icon.png`,
    fish_icon: `https://sunflower-land.com/testnet-assets/icons/fish_icon.png`,
    mine_icon: `https://sunflower-land.com/testnet-assets/icons/mine_icon.png`,
    wood_mine_icon: `https://sunflower-land.com/testnet-assets/icons/wood_mine_icon.png`,
    iron_mine_icon: `https://sunflower-land.com/testnet-assets/icons/iron_mine_icon.png`,
    money_icon: `https://sunflower-land.com/testnet-assets/icons/money_icon.png`,
  },
  npcs: {
    betty: `https://sunflower-land.com/testnet-assets/npcs/betty.gif`,
    bumpkin: `https://sunflower-land.com/testnet-assets/npcs/idle.gif`,
    fisherman: `https://sunflower-land.com/testnet-assets/npcs/fisherman.gif`,
    fishing_sheet: `https://sunflower-land.com/testnet-assets/npcs/fishing_sheet.png`,
    female_fisher: `https://sunflower-land.com/testnet-assets/npcs/female_fisher.png`,
    goblin_carry: `https://sunflower-land.com/testnet-assets/npcs/goblin_carry.gif`,
    goblin_dig: `https://sunflower-land.com/testnet-assets/npcs/goblin_dig.gif`,
    goblin_doing: `https://sunflower-land.com/testnet-assets/npcs/goblin_doing.gif`,
    goblin_farting: `https://sunflower-land.com/testnet-assets/npcs/goblin_farting.gif`,
    goblin_hammering: `https://sunflower-land.com/testnet-assets/npcs/goblin_hammering.gif`,
    goblin_hammering_sheet: `https://sunflower-land.com/testnet-assets/npcs/goblin_hammering_sheet.png`,
    goblin_jumping: `https://sunflower-land.com/testnet-assets/npcs/goblin_jumping.gif`,
    goblin_mining: `https://sunflower-land.com/testnet-assets/npcs/goblin_mining.gif`,
    goblin_swimming: `https://sunflower-land.com/testnet-assets/npcs/goblin_swimming.gif`,
    goblin_treasure: `https://sunflower-land.com/testnet-assets/npcs/goblin_treasure.gif`,
    goblin_treasure_sheet: `https://sunflower-land.com/testnet-assets/npcs/goblin_treasure_sheet.png`,
    goblin_watering: `https://sunflower-land.com/testnet-assets/npcs/goblin_watering.gif`,
    goblin: `https://sunflower-land.com/testnet-assets/npcs/goblin.gif`,
    human_carry: `https://sunflower-land.com/testnet-assets/npcs/human_carry.gif`,
    idle: `https://sunflower-land.com/testnet-assets/npcs/idle.gif`,
    moonseeker_death: `https://sunflower-land.com/testnet-assets/npcs/skeleton_death.gif`,
    moonseeker_walk: `https://sunflower-land.com/testnet-assets/npcs/skeleton_walk.gif`,
    moonseeker2: `https://sunflower-land.com/testnet-assets/npcs/skeleton2.png`,
    moonseeker3: `https://sunflower-land.com/testnet-assets/npcs/skeleton3.png`,
    moonseeker4: `https://sunflower-land.com/testnet-assets/npcs/skeleton4.png`,
    moonseeker5: `https://sunflower-land.com/testnet-assets/npcs/skeleton5.png`,
    swimmer: `https://sunflower-land.com/testnet-assets/npcs/swimmer.gif`,
    watering: `https://sunflower-land.com/testnet-assets/npcs/watering.gif`,
    wheat_goblin: `https://sunflower-land.com/testnet-assets/npcs/wheat_goblin.gif`,
  },
  resource: {
    chicken: `https://sunflower-land.com/testnet-assets/resources/chicken.png`,
    clam_shell: `https://sunflower-land.com/testnet-assets/resources/clam_shell.png`,
    coral: `https://sunflower-land.com/testnet-assets/resources/coral.png`,
    crab: `https://sunflower-land.com/testnet-assets/resources/crab.png`,
    diamond: `https://sunflower-land.com/testnet-assets/resources/diamond.png`,
    egg: `https://sunflower-land.com/testnet-assets/resources/egg.png`,
    magic_mushroom: `https://sunflower-land.com/testnet-assets/resources/magic_mushroom.png`,
    boulder: `https://sunflower-land.com/testnet-assets/resources/rare_mine.png`,
    pirate_bounty: `https://sunflower-land.com/testnet-assets/resources/pirate_bounty.webp`,
    sea_cucumber: `https://sunflower-land.com/testnet-assets/resources/sea_cucumber.png`,
    small_stone: `https://sunflower-land.com/testnet-assets/resources/small_stone.png`,
    starfish: `https://sunflower-land.com/testnet-assets/resources/starfish.png`,
    stone: `https://sunflower-land.com/testnet-assets/resources/stone.png`,
    stump: `https://sunflower-land.com/testnet-assets/resources/stump.png`,
    tree: `https://sunflower-land.com/testnet-assets/resources/tree.png`,
    spring_tree: `https://sunflower-land.com/testnet-assets/resources/spring_tree.png`,
    wild_mushroom: `https://sunflower-land.com/testnet-assets/resources/wild_mushroom.png`,
    wild_mushroom_sheet: `https://sunflower-land.com/testnet-assets/resources/wild_mushroom_sheet.png`,
    wood: `https://sunflower-land.com/testnet-assets/resources/wood.png`,
    gold_rock: `https://sunflower-land.com/testnet-assets/resources/gold_rock.png`,
    stone_rock: `https://sunflower-land.com/testnet-assets/resources/stone_rock.png`,
    iron_rock: `https://sunflower-land.com/testnet-assets/resources/iron_rock.png`,
    land: `https://sunflower-land.com/testnet-assets/resources/land.png`,
    plot: `https://sunflower-land.com/testnet-assets/resources/plot.png`,
    fruitPatch: `https://sunflower-land.com/testnet-assets/resources/fruit_patch.png`,
  },
  tools: {
    axe: `https://sunflower-land.com/testnet-assets/tools/axe.png`,
    fishing_rod: `https://sunflower-land.com/testnet-assets/tools/fishing_rod.png`,
    hammer: `https://sunflower-land.com/testnet-assets/tools/hammer.png`,
    iron_pickaxe: `https://sunflower-land.com/testnet-assets/tools/iron_pickaxe.png`,
    gold_pickaxe: `https://sunflower-land.com/testnet-assets/tools/gold_pickaxe.png`,
    power_shovel: `https://sunflower-land.com/testnet-assets/tools/power_shovel.png`,
    rusty_shovel: `https://sunflower-land.com/testnet-assets/tools/rusty_shovel.png`,
    sand_shovel: `https://sunflower-land.com/testnet-assets/tools/sand_shovel.png`,
    shovel: `https://sunflower-land.com/testnet-assets/tools/shovel.png`,
    stone_pickaxe: `https://sunflower-land.com/testnet-assets/tools/stone_pickaxe.png`,
    wood_pickaxe: `https://sunflower-land.com/testnet-assets/tools/wood_pickaxe.png`,
  },
  ui: {
    cursor: `https://sunflower-land.com/testnet-assets/ui/cursor.png`,
    round_button: `https://sunflower-land.com/testnet-assets/ui/round_button.png`,
    select_box: `https://sunflower-land.com/testnet-assets/ui/select_box.png`,
    green_bar_0: `https://sunflower-land.com/testnet-assets/ui/greenbar_00.png`,
    green_bar_1: `https://sunflower-land.com/testnet-assets/ui/greenbar_01.png`,
    green_bar_2: `https://sunflower-land.com/testnet-assets/ui/greenbar_02.png`,
    green_bar_3: `https://sunflower-land.com/testnet-assets/ui/greenbar_03.png`,
    green_bar_4: `https://sunflower-land.com/testnet-assets/ui/greenbar_04.png`,
    green_bar_5: `https://sunflower-land.com/testnet-assets/ui/greenbar_05.png`,
    green_bar_6: `https://sunflower-land.com/testnet-assets/ui/greenbar_06.png`,
    dot: `https://sunflower-land.com/testnet-assets/ui/select_dots.png`,
  },
  decorations: {
    treasure_chest: `https://sunflower-land.com/testnet-assets/decorations/treasure_chest.png`,
    treasure_chest_opened: `https://sunflower-land.com/testnet-assets/decorations/treasure_opened.png`,
    blue_bottle: `https://sunflower-land.com/testnet-assets/decorations/blue_bottle.webp`,
    orange_bottle: `https://sunflower-land.com/testnet-assets/decorations/orange_bottle.webp`,
    skull: `https://sunflower-land.com/testnet-assets/decorations/skull.webp`,
    painting: `https://sunflower-land.com/testnet-assets/decorations/painting.png`,
    rug: `https://sunflower-land.com/testnet-assets/decorations/rug.png`,
    wardrobe: `https://sunflower-land.com/testnet-assets/decorations/wardrobe.png`,
    bed: `https://sunflower-land.com/testnet-assets/decorations/bed.png`,
  },
};
